"""empty message

Revision ID: ce0f7a9b18db
Revises: 53fb2c2b5329
Create Date: 2020-10-12 13:37:55.813076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0f7a9b18db'
down_revision = '53fb2c2b5329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_pins', sa.Column('index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_pins', 'index')
    # ### end Alembic commands ###
