"""empty message

Revision ID: f25cc706be93
Revises: f36ebf760ddb
Create Date: 2020-10-13 13:16:32.939728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25cc706be93'
down_revision = 'f36ebf760ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pins', 'tags', ['tag_id'], ['id'])
    op.drop_column('pins', 'tag_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pins', sa.Column('tag_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pins', type_='foreignkey')
    op.drop_column('pins', 'tag_id')
    # ### end Alembic commands ###
