"""empty message

Revision ID: f36ebf760ddb
Revises: ce0f7a9b18db
Create Date: 2020-10-12 14:05:23.013407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36ebf760ddb'
down_revision = 'ce0f7a9b18db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('campaign_pins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_pins',
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name='campaign_pins_campaign_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='campaign_pins_tag_id_fkey'),
    sa.PrimaryKeyConstraint('campaign_id', 'tag_id', name='campaign_pins_pkey')
    )
    op.drop_table('pins')
    # ### end Alembic commands ###
