"""empty message

Revision ID: c26fab41f894
Revises: 204d32fddb89
Create Date: 2020-10-17 21:37:40.429254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26fab41f894'
down_revision = '204d32fddb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('campaign_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'campaign_id')
    # ### end Alembic commands ###
