"""empty message

Revision ID: 204d32fddb89
Revises: 7b235fbfa7a4
Create Date: 2020-10-16 18:48:11.927552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204d32fddb89'
down_revision = '7b235fbfa7a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('User', sa.NullType(), nullable=True, back_populates='tags'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'User')
    # ### end Alembic commands ###
